

ACTION_FLAG_REQUEST_NONE = 0
ACTION_FLAG_REQUEST_LOCATION = 1
ACTION_FLAG_REQUEST_CONTACTS = 2
ACTION_FLAG_BACK = 3
ACTION_FLAG_FORWARD = 4

STATIONS_PAGE_SIZE=5
SCHEDULE_PAGE_SIZE=15

MAX_DISTANCE=3